import type { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { getAuthContext } from "@/lib/auth/context";
import { can } from "@/shared/rbac/can";
import { Alert } from "@/components/ui/primitives";
import { createClient } from "@/lib/supabase/server";
import { runReport } from "@/modules/reports/services/report.service";
import { findReport } from "@/modules/reports/registry";
import { PrintTrigger } from "@/modules/reports/components/print-trigger";

export const metadata: Metadata = { title: "Print report" };

/**
 * Print-optimised report view. The user's browser turns this into a PDF, so the
 * printed document matches exactly what was on screen and we avoid shipping a
 * headless-browser rendering pipeline (docs/04 §19).
 */
export default async function ReportPrintPage({
  params,
}: {
  params: Promise<{ key: string }>;
}) {
  const { key } = await params;

  const ctx = await getAuthContext();
  if (!ctx) redirect("/login");
  if (!can(ctx, "report.read")) {
    return <Alert>You do not have permission to run reports.</Alert>;
  }

  const definition = findReport(key);
  if (!definition) notFound();

  const result = await runReport(ctx, key);
  if (!result.ok) return <Alert>{result.error.message}</Alert>;

  const supabase = await createClient();
  const { data: assembly } = await supabase
    .from("assembly")
    .select("name, district_id")
    .eq("id", ctx.assemblyId ?? "")
    .maybeSingle();

  const { rows } = result.data;
  const columns = definition.columns;
  const generated = new Date(result.data.generatedAt).toLocaleString("en-GB", {
    timeZone: "Africa/Accra",
  });

  return (
    <div className="mx-auto max-w-5xl bg-white p-8 text-black print:p-0">
      <PrintTrigger />

      <header className="mb-6 border-b border-black/20 pb-4">
        <p className="text-xs uppercase tracking-widest text-black/60">
          The Church of Pentecost
        </p>
        <h1 className="mt-1 text-xl font-bold">{assembly?.name ?? "Assembly"}</h1>
        <p className="mt-2 text-base font-semibold">{definition.name}</p>
        <p className="text-xs text-black/60">
          {rows.length} {rows.length === 1 ? "record" : "records"} · Generated {generated}
        </p>
      </header>

      <table className="w-full border-collapse text-[11px]">
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                key={c.key}
                scope="col"
                className={`border border-black/30 bg-black/5 px-2 py-1.5 text-left font-semibold ${
                  c.numeric ? "text-right" : ""
                }`}
              >
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i}>
              {columns.map((c) => (
                <td
                  key={c.key}
                  className={`border border-black/20 px-2 py-1 ${c.numeric ? "text-right" : ""}`}
                >
                  {row[c.key] ?? ""}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <footer className="mt-6 text-[10px] text-black/50">
        Generated by BEAMS · {assembly?.name ?? ""} · Confidential — for church use only.
      </footer>
    </div>
  );
}
